In [4]:
import numpy as np
RI_dict = {1: 0, 2: 0, 3: 0.58, 4: 0.90, 5: 1.12, 6: 1.24, 7: 1.32, 8: 1.41, 9: 1.45}
def AHP(A_arr):     #求特征向量
    A = np.array(A_arr)
#将矩阵列向量进行单位化0
    a_sum0 = A.sum(axis=0)
    B = A / a_sum0  
    

    b_sum = B.sum(axis=1)
    W = b_sum.sum()
    w_arr = []
    for w in b_sum:
        w_arr.append(w/W)
    print('特征向量为: %s' % w_arr)
    #一致性检验
    AW = []
    for a in A :
        aa = a * w_arr
        AW.append(aa.sum())
    result = np.array(AW) / np.array(w_arr)
    row = result.shape[0]
    Max = result.sum()/row
    print('最大特征值λMax: %s' % Max)
    CI = (Max - row) / (row - 1)
   
    CR = CI / RI_dict[row]
    print('CR: %s' % CR)
    if (CR<0.1): print('通过一致性检验！')
    else: print('未通过一致性检验！')


In [5]:
import pandas as pd
df = pd.read_excel("AHP_data.xlsx")
A=df.iloc[:,1:6].values
AHP(A)

特征向量为: [0.10051698109982732, 0.04119232069791139, 0.17001621264746442, 0.35780509024914975, 0.3304693953056471]
最大特征值λMax: 5.179341953712946
CR: 0.040031686096639714
通过一致性检验！


In [6]:
w=[0.10051698109982732, 0.04119232069791139, 0.17001621264746442, 0.35780509024914975, 0.3304693953056471]

In [7]:
dataset=pd.read_excel("customer_data_V4.xlsx")
Y=dataset.iloc[:,-1].values
dataset.head()

ID  age  marital    income  house  business  property  debt  job  credit  \
0  C001  1.0      1.0  0.333333    1.0       0.0  0.727273   1.0    1     0.0   
1  C002  1.0      1.0  0.333333    1.0       0.5  1.000000   1.0    1     1.0   
2  C003  1.0      1.0  1.000000    1.0       0.5  0.727273   0.5    1     0.8   
3  C004  1.0      1.0  0.000000    1.0       0.0  0.363636   1.0    0     1.0   
4  C005  1.0      1.0  0.333333    1.0       0.0  0.363636   0.5    1     0.8   

   relation  class  
0      0.50      1  
1      0.75      1  
2      0.75      1  
3      0.00      0  
4      0.00      0

In [8]:
from sklearn.preprocessing import MinMaxScaler
X1=dataset.iloc[:,[1,4]].values #个人情况
print("选择age与house")

选择age与house


In [9]:
w1=np.array([1,2]).T
x1=np.dot(X1,w1)
s1=MinMaxScaler()

In [10]:
X2=dataset.iloc[:,[2,10]].values #家庭情况
x2=np.dot(X2,np.array([1,3]).T)
print("选择marital与relation")

选择marital与relation


In [11]:
X3=dataset.iloc[:,[3,6,7]].values #财务情况
x3=np.dot(X3,np.array([1,2,-0.5]).T)
print("选择income，property和debt")

选择income，property和debt


In [12]:
X4=dataset.iloc[:,[5,8]] #职业情况
X4.head()

business  job
0       0.0    1
1       0.5    1
2       0.5    1
3       0.0    0
4       0.0    1

In [13]:
x4=np.dot(X4,np.array([1,1]).T)

In [14]:
X5=dataset.iloc[:,[9]] #信用记录
X5.head()

credit
0     0.0
1     1.0
2     0.8
3     1.0
4     0.8

In [15]:
x5=dataset.iloc[:,[9]].values
x5=np.dot(X5,np.array([1]).T)

In [16]:
m=[x1,x2,x3,x4,x5]
m=np.array(m)
pred=np.dot(m.T,np.array(w))

In [17]:
pred

array([0.98129711, 1.61429941, 1.61131761, 0.71185271, 1.10274004,
       1.39791514, 1.18811835, 0.78488673, 0.80037201, 1.47613083,
       1.52161668, 1.44523659, 0.99491865, 1.07175114, 1.11567287,
       1.53192663, 0.87281731, 1.14447377, 1.23913853, 1.1919651 ,
       1.00409939, 1.75853779, 1.41684734, 1.06023599, 1.70835912,
       1.36983846, 1.55111104, 1.44436032, 1.59970779, 1.22883452,
       1.08851881, 1.63621916, 0.99491865, 1.44262517, 1.41945876,
       1.24856034, 1.5447831 , 1.28543612, 1.25718777, 1.12632987,
       1.06023599, 1.37863071, 0.66444925, 1.29577537, 1.03070639,
       1.23305147, 1.04039825, 0.95971901, 1.57828876, 1.56886695,
       1.1637582 , 1.52375129, 1.53071491, 1.58472876, 1.0049816 ,
       1.10274004, 0.99491865, 1.22117712, 1.3795837 , 1.30523241,
       1.70835912, 1.450353  , 1.67741149, 1.4546584 , 1.57311895,
       0.76852478, 1.42888057, 1.29577537, 1.25216603, 1.54053091,
       1.10003396, 1.42113476, 0.95093834, 1.22507647, 1.29316

In [18]:
result=np.arange(len(pred))
for i in range(len(pred)):
    if pred[i]>0.89: result[i]=1
    else : result[i]=0
result

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,

In [19]:
Y

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,

In [20]:
from sklearn.metrics import confusion_matrix
M=confusion_matrix(Y,result)
M

array([[ 40, 212],
       [  0, 288]], dtype=int64)

In [21]:
p_neur = (M[0,0]+M[1,1])/(M[0,0]+M[1,1]+M[0,1]+M[1,0])
print("准确度：",p_neur)

准确度： 0.6074074074074074
